#ifndef BILILIVE_BILILIVE_FIRST_RUN_D3D_COMPONENTS_VALIDATION_H_
#define BILILIVE_BILILIVE_FIRST_RUN_D3D_COMPONENTS_VALIDATION_H_

namespace bililive {

int ValidateD3DComponent();

}   // namespace bililive

#endif  // BILILIVE_BILILIVE_FIRST_RUN_D3D_COMPONENTS_VALIDATION_H_