#ifndef BILILIVE_BILILIVE_UI_EXAMPLES_EXAMPLES_RUNNER_H_
#define BILILIVE_BILILIVE_UI_EXAMPLES_EXAMPLES_RUNNER_H_


class ExamplesRunner {
public:
    int Run();
};

#endif  // BILILIVE_BILILIVE_UI_EXAMPLES_EXAMPLES_RUNNER_H_